### PR TITLE
converts NSNull, NSArray, NSDictionary, NSDate and NSData

### PR DESCRIPTION
**Pull request by Lessica**
### Changes
- `NSString <=> string`
- `NSNumber <=> number`, but `NaN` is not allowed anymore (`Int64` and `UInt64` are not considered)
- `NSNumber <= boolean`
- `NSArray <=> Array`
- `NSDictionary <=> Object`
- `NSDate <=> Date`
- `NSData <=> ArrayBuffer`
- `NSNull <=> null` only when `null` is wrapped in `NSArray` or `NSDictionary`
- fully tested without bumping version

### Issues
- cannot detect infinite recursion
- overrides `.valueOf`, which may cause compatibility issues
- `NSRegularExpression <=> RegExp` is not implemented due to the regex syntax difference
- objc class caching needs to be improved, too many variables :-/
- writing tests with multi-line c strings drives me crazy!

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks for doing this! :heart:

I've been thinking about implementing this previously, but there was one thing that was bugging me: if we make it this easy to implicitly create short-lived Objective-C objects from JavaScript values, we make it really easy to introduce performance bottlenecks. Whereas currently it's very clear to the developer that instantiating such values has a cost, so they might opt to do that only once and recycle the values. There is also the added cost of having to sniff values.

So I wonder if we should instead go for something like `ObjC.Object.from(value)`, where `value` can be a lot of things. That way it's very explicit, and the user is more likely to be conscious of the performance cost.

What do you think?

**Comment by Lessica** [comment]
You are right. But I just made it a bit further, but **it's still far from the final stage**. 😆

At the first time when I read [Javascript API Docs](https://frida.re/docs/javascript-api/), I was confused. There's only the bridge from `ObjC` to `JS` (`ObjC.Object`), but no explicit API creates bridge from `JS` to `ObjC`. Meanwhile, this example [Displaying an alert box on iOS >= 8](https://frida.re/docs/examples/ios/) indicates that  there's a "hidden" bridge from `string` to `NSString`.

I found the implementation here, and I realized that, actually, there's no bridge converts between basic ObjC types and common JS values except `NSString<=>string` and `NSNumber (double)<=number`. The `toString()` / `valueOf()` only prints the description of `NSObject`. That's too strange and not friendly to anyone new to Frida. Frida is a huge project, but its documentation is too... I can't even make a search of it 🤔

Years ago, I wrote a bridge from Lua to ObjC implemented in Lua C module, not in FFI layer, though I had to manually alloc and release the memory, it was fast and stable. I think it would be better if such bridge can be implemented in `duktape` or `V8` as an extension, if it is possible.

**Comment by oleavr** [comment]
@Lessica Sorry for dropping the ball here, got distracted by other things, and I'm (obviously) terrible at context-switching. 😞

Totally agree with you. I think we should address the gaps going from `JS` to `ObjC`, and we need more docs. As for the "hidden" bridging of `string` to `NSString`, that's definitely an inconsistency that I'm not super-happy about. But OTOH maybe it isn't so bad to keep going down that road if we can make the overhead negligible.

The reason that the built-in FFI is very primitive is that I'm trying to keep Frida's core very minimal, so it only contains building blocks that are common to the majority of use-cases. Basically my worry is that once we start adding language-specific features in, we can keep going until we've created a ten-headed monster. 😅 But making it extensible could have a lot of potential, so I'm definitely open to that.

By the way, we now finally have [CModule](https://frida.re/news/2019/09/18/frida-12-7-released/) that seems to have a lot of potential for dealing with bottlenecks. I took it for a spin back in September, where I [optimized](https://github.com/frida/frida-objc-bridge/commit/69ad9c82f0abb6d69563638f55acfa81dae21082) `Java.choose()` and made it ~100x faster. I recently also introduced some optimizations in frida-java-bridge's [ClassModel](https://github.com/frida/frida-java-bridge/blob/master/lib/class-model.js) allowing us to index a given class very quickly, to allow querying that index from JS lazily. (By using `Proxy` objects.) We still have a lot of room for optimization both here and in frida-java-bridge, though 😊

**Comment by oleavr** [comment]
Let's get this merged – I'm going to land this PR before the upcoming release. Should happen in the next few days if things go as planned 🙂

**Comment by oleavr** [comment]
(Since it's been so long since this was submitted (my bad) I'm going to make the final tweaks needed before merging.)

**Pull request closed without merging**
